apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Kubernetes + Helm</title>
    </head>
    <body>
      <h1>{{ .Values.config.mensaje }}</h1>
      <p>Gestionado mediante Helm Chart.</p>
    </body>
    </html>